name: Test
on: [push]  # Triggered on every push to the repo
jobs:
  build:
    runs-on: ubuntu-latest
    # что делаем
    steps:
      - uses: actions/checkout@3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:  # ← был пропущен 'with'
          distribution: 'zulu'
          java-version: '24'

      - name: Run tests
        run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub